-- MySQL Script generated by MySQL Workbench
-- Wed Oct 18 08:08:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema athenas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema athenas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `athenas` DEFAULT CHARACTER SET latin1 ;
USE `athenas` ;

-- -----------------------------------------------------
-- Table `athenas`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `athenas`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `athenas`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(245) NULL,
  `email` VARCHAR(245) NULL,
  `tipo` VARCHAR(45) NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
